// <auto-generated />
using System;
using FinancesBackend.Efc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apartment_back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221209094742_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancesBackend.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("Square")
                        .HasColumnType("int");

                    b.Property<string>("ID_apartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                   

                    b.ToTable("Percentage");

                    b.HasData(
                        new
                        {
                            Id_apartment = 1,
                            Square = "25",
                            Price = 20000.75,
                            Location = Lvivska_12,
                            Category = Category.Square
                        },
                        new
                        {
                            Id_apartment = 2,
                            Square = "55",
                            Price = 24000.75,
                            Location = Lvivska_42,
                            Category = Category.Price
                        },
                        new
                        {
                            Id_apartment = 3,
                            Square = "35",
                            Price = 15000.75,
                            Location = Lvivska_22,
                            Category = Category.Area
                        },
                        
                });
#pragma warning restore 612, 618
        }
    }
}
